Please cite this work as:

Smith, Ericka B., 2020. "2650 Miles: Bootstrapping the Pacific Crest Trail in Parallel". [https://github.com/ST541-Fall2020/erickabsmith-project-trail](https://github.com/ST541-Fall2020/erickabsmith-project-trail)


## Data Source

Pacific Crest Trail Association: [PCT visitor use statistics](https://www.pcta.org/our-work/trail-and-land-management/pct-visitor-use-statistics/) and [2,600 miler list](https://www.pcta.org/discover-the-trail/thru-hiking-long-distance-hiking/2600-miler-list/)


## Specific Resources or Sites Used

Wilson G, Bryan J, Cranston K, Kitzes J, Nederbragt L, Teal TK (2017) Good enough practices in scientific computing. PLoS Comput Biol 13(6): e1005510. https://doi.org/10.1371/journal.pcbi.1005510

[https://davisvaughan.github.io/furrr/](https://davisvaughan.github.io/furrr/)

[https://davisvaughan.github.io/furrr/articles/articles/remote-connections.html](https://davisvaughan.github.io/furrr/articles/articles/remote-connections.html)

[https://github.com/HenrikBengtsson/future](https://github.com/HenrikBengtsson/future)

[https://blog.davisvaughan.com/2017/05/15/rstudio-shiny-aws-1/](https://blog.davisvaughan.com/2017/05/15/rstudio-shiny-aws-1/)

[https://www.louisaslett.com/RStudio_AMI/](https://www.louisaslett.com/RStudio_AMI/)

[https://rstudio.com/products/rstudio/download-server/debian-ubuntu/](https://rstudio.com/products/rstudio/download-server/debian-ubuntu/)

[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html)

[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connection-prereqs.html](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connection-prereqs.html)

[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html#TroubleshootingInstancesConnectingPuTTY](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html#TroubleshootingInstancesConnectingPuTTY)


## Package Citations

 **Alboukadel Kassambara (2020). ggpubr: 'ggplot2' Based Publication Ready Plots. R package version 0.3.0. https://CRAN.R-project.org/package=ggpubr**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {ggpubr: 'ggplot2' Based Publication Ready Plots},
    author = {Alboukadel Kassambara},
    year = {2020},
    note = {R package version 0.3.0},
    url = {https://CRAN.R-project.org/package=ggpubr},
  } 

  **Davis Vaughan and Matt Dancho (2020). furrr: Apply Mapping Functions in Parallel using Futures. R package version 0.2.1. https://CRAN.R-project.org/package=furrr**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {furrr: Apply Mapping Functions in Parallel using Futures},
    author = {Davis Vaughan and Matt Dancho},
    year = {2020},
    note = {R package version 0.2.1},
    url = {https://CRAN.R-project.org/package=furrr},
  }

  **Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2020). dplyr: A Grammar of Data Manipulation. R package version 0.8.5.**
  https://CRAN.R-project.org/package=dplyr

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {dplyr: A Grammar of Data Manipulation},
    author = {Hadley Wickham and Romain François and Lionel Henry and Kirill Müller},
    year = {2020},
    note = {R package version 0.8.5},
    url = {https://CRAN.R-project.org/package=dplyr},
  }
  
  **Hadley Wickham. testthat: Get Started with Testing. The R Journal, vol. 3, no. 1, pp. 5--10, 2011**

A BibTeX entry for LaTeX users is

  @Article{,
    author = {Hadley Wickham},
    title = {testthat: Get Started with Testing},
    journal = {The R Journal},
    year = {2011},
    volume = {3},
    pages = {5--10},
    url = {https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf},
  }
  
  **Hadley Wickham and Jennifer Bryan (2020). usethis: Automate Package and Project Setup. R package version 1.6.3. https://CRAN.R-project.org/package=usethis**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {usethis: Automate Package and Project Setup},
    author = {Hadley Wickham and Jennifer Bryan},
    year = {2020},
    note = {R package version 1.6.3},
    url = {https://CRAN.R-project.org/package=usethis},
  }

  **Hao Zhu (2020). kableExtra: Construct Complex Table with 'kable' and Pipe Syntax. R package version 1.3.1. https://CRAN.R-project.org/package=kableExtra**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {kableExtra: Construct Complex Table with 'kable' and Pipe Syntax},
    author = {Hao Zhu},
    year = {2020},
    note = {R package version 1.3.1},
    url = {https://CRAN.R-project.org/package=kableExtra},
  }

  **H. Bengtsson, A Unifying Framework for Parallel and Distributed Processing in R using Futures, arXiv:2008.00553, 2020**

A BibTeX entry for LaTeX users is

  @Misc{,
    author = {Henrik Bengtsson},
    title = {A Unifying Framework for Parallel and Distributed Processing in R using Futures},
    year = {2020},
    month = {aug},
    eprint = {2008.00553},
    archiveprefix = {arXiv},
    primaryclass = {cs.DC},
    url = {https://arxiv.org/abs/2008.00553},
  }
  
  **Henrik Bengtsson (2020). parallelly: Enhancing the 'parallel' Package. R package version 1.21.0. https://CRAN.R-project.org/package=parallelly**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {parallelly: Enhancing the 'parallel' Package},
    author = {Henrik Bengtsson},
    year = {2020},
    note = {R package version 1.21.0},
    url = {https://CRAN.R-project.org/package=parallelly},
  }

  **Jeroen Ooms (2020). magick: Advanced Graphics and Image-Processing in R. R package version 2.5.2. https://CRAN.R-project.org/package=magick**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {magick: Advanced Graphics and Image-Processing in R},
    author = {Jeroen Ooms},
    year = {2020},
    note = {R package version 2.5.2},
    url = {https://CRAN.R-project.org/package=magick},
  }


  **Kirill Müller (2017). here: A Simpler Way to Find Your Files. R package version 0.1. https://CRAN.R-project.org/package=here**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {here: A Simpler Way to Find Your Files},
    author = {Kirill Müller},
    year = {2017},
    note = {R package version 0.1},
    url = {https://CRAN.R-project.org/package=here},
  }
 
   **Lionel Henry and Hadley Wickham (2020). purrr: Functional Programming Tools. R package version 0.3.4. https://CRAN.R-project.org/package=purrr**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {purrr: Functional Programming Tools},
    author = {Lionel Henry and Hadley Wickham},
    year = {2020},
    note = {R package version 0.3.4},
    url = {https://CRAN.R-project.org/package=purrr},
  }
 
  **Max Kuhn, Fanny Chow and Hadley Wickham (2020). rsample: General Resampling Infrastructure. R package version 0.0.8. https://CRAN.R-project.org/package=rsample**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {rsample: General Resampling Infrastructure},
    author = {Max Kuhn and Fanny Chow and Hadley Wickham},
    year = {2020},
    note = {R package version 0.0.8},
    url = {https://CRAN.R-project.org/package=rsample},
  }
  
  **Nan Xiao (2019). liftr: Containerize R Markdown Documents for Continuous Reproducibility. R package version 0.9.2. https://CRAN.R-project.org/package=liftr**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {liftr: Containerize R Markdown Documents for Continuous Reproducibility},
    author = {Nan Xiao},
    year = {2019},
    note = {R package version 0.9.2},
    url = {https://CRAN.R-project.org/package=liftr},
  }
 
  **Stefan Milton Bache and Hadley Wickham (2014). magrittr: A Forward-Pipe Operator for R. R package version 1.5. https://CRAN.R-project.org/package=magrittr**

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {magrittr: A Forward-Pipe Operator for R},
    author = {Stefan Milton Bache and Hadley Wickham},
    year = {2014},
    note = {R package version 1.5},
   
 
 
  **Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686, https://doi.org/10.21105/joss.01686**

A BibTeX entry for LaTeX users is

  @Article{,
    title = {Welcome to the {tidyverse}},
    author = {Hadley Wickham and Mara Averick and Jennifer Bryan and Winston Chang and Lucy D'Agostino McGowan and Romain François and Garrett Grolemund and Alex Hayes and Lionel Henry and Jim Hester and Max Kuhn and Thomas Lin Pedersen and Evan Miller and Stephan Milton Bache and Kirill Müller and Jeroen Ooms and David Robinson and Dana Paige Seidel and Vitalie Spinu and Kohske Takahashi and Davis Vaughan and Claus Wilke and Kara Woo and Hiroaki Yutani},
    year = {2019},
    journal = {Journal of Open Source Software},
    volume = {4},
    number = {43},
    pages = {1686},
    doi = {10.21105/joss.01686},
  }