---
title: "Good Enough Practices in Scientific Computing"
output: github_document
---

From Wilson G, Bryan J, Cranston K, Kitzes J, Nederbragt L, et al. (2017) *Good enough practices in scientific computing.* PLOS Computational Biology 13(6): e1005510. https://doi.org/10.1371/journal.pcbi.1005510

## Overview

Computing workflows are woefully undertaught in science.

Box 1. Summary of practices (verbatim copy of manuscript here)

1. Data management
  * Save the raw data.
  * Ensure that raw data are backed up in more than one location.
  * Create the data you wish to see in the world.
  * Create analysis-friendly data.
  * Record all the steps used to process data.
  * Anticipate the need to use multiple tables, and use a unique identifier for every record.
  * Submit data to a reputable DOI-issuing repository so that others can access and cite it.
2. Software
  * Place a brief explanatory comment at the start of every program.
  * Decompose programs into functions.
  * Be ruthless about eliminating duplication.
  * Always search for well-maintained software libraries that do what you need.
  * Test libraries before relying on them.
  * Give functions and variables meaningful names.
  * Make dependencies and requirements explicit.
  * Do not comment and uncomment sections of code to control a program's behavior.
  * Provide a simple example or test data set.
  * Submit code to a reputable DOI-issuing repository.
3. Collaboration
  * Create an overview of your project.
  * Create a shared "to-do" list for the project.
  * Decide on communication strategies.
  * Make the license explicit.
  * Make the project citable.
4. Project organization
  * Put each project in its own directory, which is named after the project.
  * Put text documents associated with the project in the doc directory.
  * Put raw data and metadata in a data directory and files generated during cleanup and analysis in a results directory.
  * Put project source code in the src directory.
  * Put external scripts or compiled programs in the bin directory.
  * Name all files to reflect their content or function.
5. Keeping track of changes
  * Back up (almost) everything created by a human being as soon as it is created.
  * Keep changes small.
  * Share changes frequently.
  * Create, maintain, and use a checklist for saving and sharing changes to the project.
  * Store each project in a folder that is mirrored off the researcher's working machine.
  * Add a file called CHANGELOG.txt to the project's docs subfolder.
  * Copy the entire project whenever a significant change has been made.
  * Use a version control system.
6. Manuscripts
  * Write manuscripts using online tools with rich formatting, change tracking, and reference management.
  * Write the manuscript in a plain text format that permits version control.
  
  
## Data Management

* Think about open file formats:
  * Tabular
    * csv
  * Not tabular (like graphs)
    * XML (Extensible Markup Language) - "carries the data but does not present it" ??
    * YAML (YAML ain't markup language) - similar to xml
    * JSON (JavaScript Object Notation) - a data interchange format machines to humans.. .also similar to the above two? 
  * Certain Kinds of Structured Data
    * HDF5 (Hierarchical Data Format) - large complex heterogeneous data
* Tidy data
  * one row per observation
  * each column a variable
* Unique identifiers


## Software

* Explanatory comment start of **every** program
* make functions not programs
* be clear about requirements and dependencies
* commenting is for comments not code

## Collaboration

* README "should contain the project's title, a brief description, up-to-date contact information, and an example or 2 of how to run various cleaning or analysis tasks... make it explicit how you want people to engage with the project."


## Project Organization

Example (verbatim from article):

`|-- CITATION`

`|-- README`

`|-- LICENSE`

`|-- requirements.txt`

`|-- data`

`|  |-- birds_count_table.csv`

`|-- doc`

`|  |-- notebook.md`

`|  |-- manuscript.md`

`|  |-- changelog.txt`

`|-- results`

`|  |-- summarized_results.csv`

`|-- src`

`|  |-- sightings_analysis.py`

`|  |-- runall.py`


## Keeping track of changes

* update your versions often


## Manuscripts

* google docs are a nice compromise between LaTeX and downloading versions + word
